#!/usr/bin/env node
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const VERSION = "17.0.0";
const GENERATOR_VERSION = 1;
const SOURCE_NAMES = [
  "UnicodeData.txt", "DerivedCoreProperties.txt", "PropList.txt",
  "SpecialCasing.txt", "CaseFolding.txt", "CompositionExclusions.txt",
  "NormalizationTest.txt"
];
const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, "../../../../..");
const defaults = {
  ucd: join(here, "ucd", VERSION),
  js: join(repo, "examples/05_stdlib/spipe/src/search/generated/unicode_17_0_0.js"),
  simple: join(repo, "src/lib/common/search/generated/unicode_17_0_0.spl"),
  manifest: join(repo, "examples/05_stdlib/spipe/test/fixture/wave4_search/unicode_17_0_0_manifest.json")
};

function args() {
  const out = { ...defaults };
  for (let i = 2; i < process.argv.length; i += 2) {
    const key = process.argv[i];
    if (!Object.hasOwn({ "--ucd-dir": 1, "--js-out": 1, "--simple-out": 1, "--manifest-out": 1 }, key))
      throw new Error(`unknown argument: ${key}`);
    if (!process.argv[i + 1]) throw new Error(`missing value for ${key}`);
    out[{ "--ucd-dir": "ucd", "--js-out": "js", "--simple-out": "simple", "--manifest-out": "manifest" }[key]] = resolve(process.argv[i + 1]);
  }
  return out;
}

const sha = (bytes) => createHash("sha256").update(bytes).digest("hex");
const strip = (line) => line.replace(/#.*/, "").trim();
const cps = (text) => text.trim() ? text.trim().split(/\s+/).map((v) => Number.parseInt(v, 16)) : [];
const hex = (n) => n.toString(16).toUpperCase().padStart(4, "0");

function parseRange(text) {
  const [a, b = a] = text.trim().split("..").map((v) => Number.parseInt(v, 16));
  return [a, b];
}

function mergeRanges(ranges) {
  const sorted = ranges.toSorted((a, b) => a[0] - b[0] || a[1] - b[1]);
  const out = [];
  for (const [start, end] of sorted) {
    const last = out.at(-1);
    if (last && start <= last[1] + 1) last[1] = Math.max(last[1], end);
    else out.push([start, end]);
  }
  return out;
}

function parseProperty(text, wanted) {
  const ranges = [];
  for (const raw of text.split(/\r?\n/)) {
    const line = strip(raw);
    if (!line) continue;
    const [range, property] = line.split(";").map((v) => v.trim());
    if (property === wanted) ranges.push(parseRange(range));
  }
  return mergeRanges(ranges);
}

function parseUnicodeData(text) {
  const records = [];
  let pending = null;
  for (const raw of text.split(/\r?\n/)) {
    if (!raw) continue;
    const f = raw.split(";");
    const cp = Number.parseInt(f[0], 16);
    if (f[1].endsWith(", First>")) { pending = { cp, f }; continue; }
    if (f[1].endsWith(", Last>")) {
      if (!pending) throw new Error(`range end without start at ${f[0]}`);
      for (let value = pending.cp; value <= cp; value++) records.push({ cp: value, f: pending.f });
      pending = null;
    } else records.push({ cp, f });
  }
  if (pending) throw new Error("unterminated UnicodeData range");
  return records;
}

function renderJs(meta, tables) {
  return `// Generated by tools/unicode/generate_unicode_tables.mjs; do not edit.\n` +
    `// Unicode License v3: ../../../../tools/unicode/UNICODE-LICENSE.txt\n` +
    `export const UNICODE_TABLE_METADATA = Object.freeze(${JSON.stringify(meta)});\n` +
    Object.entries(tables).map(([name, value]) =>
      `export const ${name} = Object.freeze(${JSON.stringify(value)});`).join("\n") + `\n${JS_RUNTIME}`;
}

function compact(value) {
  return JSON.stringify(value).replaceAll("true", "1").replaceAll("false", "0");
}

const JS_RUNTIME = String.raw`
function rangeContains(ranges, cp) {
  if (!Number.isInteger(cp) || cp < 0 || cp > 0x10ffff) return false;
  let lo = 0, hi = ranges.length - 1;
  while (lo <= hi) {
    const mid = (lo + hi) >>> 1, range = ranges[mid];
    if (cp < range[0]) hi = mid - 1;
    else if (cp > range[1]) lo = mid + 1;
    else return true;
  }
  return false;
}
function exactLookup(rows, cp, fallback) {
  let lo = 0, hi = rows.length - 1;
  while (lo <= hi) {
    const mid = (lo + hi) >>> 1, found = rows[mid][0];
    if (cp < found) hi = mid - 1;
    else if (cp > found) lo = mid + 1;
    else return rows[mid];
  }
  return fallback;
}
export const unicodeIsAlphabetic = (cp) => rangeContains(ALPHABETIC_RANGES, cp);
export const unicodeIsDecimalNumber = (cp) => rangeContains(DECIMAL_NUMBER_RANGES, cp);
export const unicodeIsMark = (cp) => rangeContains(MARK_RANGES, cp);
export const unicodeIsTokenCodePoint = (cp) => cp === 0x5f || unicodeIsAlphabetic(cp) || unicodeIsDecimalNumber(cp) || unicodeIsMark(cp);
export const unicodeCanonicalCombiningClass = (cp) => exactLookup(CANONICAL_COMBINING_CLASS, cp, [0, 0])[1];
const decomposition = new Map(CANONICAL_DECOMPOSITIONS);
const lowercase = new Map(DEFAULT_LOWERCASE.map(([cp, mapping, conditionalMapping, condition]) => [cp, { mapping, conditionalMapping, condition }]));
function decomposeOne(cp, output) {
  const h = HANGUL_NFC, nCount = h.v_count * h.t_count, sIndex = cp - h.s_base;
  if (sIndex >= 0 && sIndex < h.l_count * nCount) {
    output.push(h.l_base + Math.floor(sIndex / nCount), h.v_base + Math.floor((sIndex % nCount) / h.t_count));
    if (sIndex % h.t_count) output.push(h.t_base + (sIndex % h.t_count));
    return;
  }
  const mapping = decomposition.get(cp);
  if (mapping) for (const part of mapping) decomposeOne(part, output);
  else output.push(cp);
}
function composePair(a, b) {
  const h = HANGUL_NFC, nCount = h.v_count * h.t_count;
  const lIndex = a - h.l_base, vIndex = b - h.v_base;
  if (lIndex >= 0 && lIndex < h.l_count && vIndex >= 0 && vIndex < h.v_count)
    return h.s_base + (lIndex * h.v_count + vIndex) * h.t_count;
  const sIndex = a - h.s_base, tIndex = b - h.t_base;
  if (sIndex >= 0 && sIndex < h.l_count * nCount && sIndex % h.t_count === 0 && tIndex > 0 && tIndex < h.t_count) return a + tIndex;
  let lo = 0, hi = CANONICAL_COMPOSITIONS.length - 1;
  while (lo <= hi) {
    const mid = (lo + hi) >>> 1, row = CANONICAL_COMPOSITIONS[mid];
    if (a < row[0] || (a === row[0] && b < row[1])) hi = mid - 1;
    else if (a > row[0] || (a === row[0] && b > row[1])) lo = mid + 1;
    else return row[2];
  }
  return undefined;
}
export function unicodeNormalizeNfc(text) {
  const values = [];
  for (const char of text) {
    const cp = char.codePointAt(0);
    if (cp >= 0xd800 && cp <= 0xdfff) throw new TypeError("input must contain only Unicode scalar values");
    decomposeOne(cp, values);
  }
  for (let i = 1; i < values.length; i++) {
    const cls = unicodeCanonicalCombiningClass(values[i]);
    if (!cls) continue;
    let j = i;
    while (j > 0 && unicodeCanonicalCombiningClass(values[j - 1]) > cls) { [values[j - 1], values[j]] = [values[j], values[j - 1]]; j--; }
  }
  if (!values.length) return "";
  const output = [values[0]];
  let starterIndex = 0, starter = output[0], lastClass = 0;
  for (let i = 1; i < values.length; i++) {
    const cp = values[i], cls = unicodeCanonicalCombiningClass(cp), composite = composePair(starter, cp);
    if (composite !== undefined && (lastClass < cls || lastClass === 0)) output[starterIndex] = starter = composite;
    else { if (cls === 0) { starterIndex = output.length; starter = cp; } output.push(cp); lastClass = cls; }
  }
  return String.fromCodePoint(...output);
}
function isFinalSigma(values, index) {
  let before = false;
  for (let i = index - 1; i >= 0; i--) {
    if (rangeContains(CASE_IGNORABLE_RANGES, values[i])) continue;
    before = rangeContains(CASED_RANGES, values[i]); break;
  }
  if (!before) return false;
  for (let i = index + 1; i < values.length; i++) {
    if (rangeContains(CASE_IGNORABLE_RANGES, values[i])) continue;
    return !rangeContains(CASED_RANGES, values[i]);
  }
  return true;
}
export function unicodeDefaultLowercase(text) {
  const values = [...unicodeNormalizeNfc(text)].map((char) => char.codePointAt(0)), output = [];
  for (let i = 0; i < values.length; i++) {
    const entry = lowercase.get(values[i]);
    if (!entry) output.push(values[i]);
    else if (entry.condition === "Final_Sigma" && isFinalSigma(values, i)) output.push(...entry.conditionalMapping);
    else output.push(...entry.mapping);
  }
  return unicodeNormalizeNfc(String.fromCodePoint(...output));
}
`;

const flatten = (rows) => rows.flat(Infinity);
const simpleArray = (name, values) => `val ${name}: [i64] = ${JSON.stringify(values)}`;
function offsetData(rows, select) {
  const offsets = [0], data = [];
  for (const row of rows) { data.push(...select(row)); offsets.push(data.length); }
  return { offsets, data };
}

function renderSimple(meta, tables) {
  const decomp = offsetData(tables.CANONICAL_DECOMPOSITIONS, (row) => row[1]);
  const lower = offsetData(tables.DEFAULT_LOWERCASE, (row) => row[1]);
  const conditional = offsetData(tables.DEFAULT_LOWERCASE, (row) => row[2] ?? []);
  const lines = [
    "# Generated by examples/05_stdlib/spipe/tools/unicode/generate_unicode_tables.mjs; do not edit.",
    "# Unicode License v3: examples/05_stdlib/spipe/tools/unicode/UNICODE-LICENSE.txt",
    `val unicode_table_version = \"${VERSION}\"`,
    `val unicode_table_generator_sha256 = \"${meta.generator_sha256}\"`,
    "use std.common.encoding.utf8.{text_codepoints, text_from_codepoints}",
    simpleArray("_unicode_alphabetic_ranges", flatten(tables.ALPHABETIC_RANGES)),
    simpleArray("_unicode_decimal_ranges", flatten(tables.DECIMAL_NUMBER_RANGES)),
    simpleArray("_unicode_mark_ranges", flatten(tables.MARK_RANGES)),
    simpleArray("_unicode_cased_ranges", flatten(tables.CASED_RANGES)),
    simpleArray("_unicode_case_ignorable_ranges", flatten(tables.CASE_IGNORABLE_RANGES)),
    simpleArray("_unicode_ccc_keys", tables.CANONICAL_COMBINING_CLASS.map((row) => row[0])),
    simpleArray("_unicode_ccc_values", tables.CANONICAL_COMBINING_CLASS.map((row) => row[1])),
    simpleArray("_unicode_decomposition_keys", tables.CANONICAL_DECOMPOSITIONS.map((row) => row[0])),
    simpleArray("_unicode_decomposition_offsets", decomp.offsets),
    simpleArray("_unicode_decomposition_data", decomp.data),
    simpleArray("_unicode_composition_data", flatten(tables.CANONICAL_COMPOSITIONS)),
    simpleArray("_unicode_lowercase_keys", tables.DEFAULT_LOWERCASE.map((row) => row[0])),
    simpleArray("_unicode_lowercase_offsets", lower.offsets),
    simpleArray("_unicode_lowercase_data", lower.data),
    simpleArray("_unicode_lowercase_conditional_offsets", conditional.offsets),
    simpleArray("_unicode_lowercase_conditional_data", conditional.data),
    simpleArray("_unicode_lowercase_conditions", tables.DEFAULT_LOWERCASE.map((row) => row[3] === "Final_Sigma" ? 1 : 0)),
    SIMPLE_RUNTIME
  ];
  return `${lines.join("\n")}\n`;
}

const SIMPLE_RUNTIME = String.raw`
fn _unicode_range_contains(ranges: [i64], cp: i64) -> bool:
    var low: i64 = 0
    var high: i64 = ranges.len() / 2 - 1
    while low <= high:
        val mid = (low + high) / 2
        val start = ranges[mid * 2]
        val finish = ranges[mid * 2 + 1]
        if cp < start: high = mid - 1
        elif cp > finish: low = mid + 1
        else: return true
    false

fn _unicode_find(keys: [i64], cp: i64) -> i64:
    var low: i64 = 0
    var high: i64 = keys.len() - 1
    while low <= high:
        val mid = (low + high) / 2
        if cp < keys[mid]: high = mid - 1
        elif cp > keys[mid]: low = mid + 1
        else: return mid
    -1

fn unicode_is_alphabetic(cp: i64) -> bool: _unicode_range_contains(_unicode_alphabetic_ranges, cp)
fn unicode_is_decimal_number(cp: i64) -> bool: _unicode_range_contains(_unicode_decimal_ranges, cp)
fn unicode_is_mark(cp: i64) -> bool: _unicode_range_contains(_unicode_mark_ranges, cp)
fn unicode_is_token_code_point(cp: i64) -> bool:
    cp == 95 or unicode_is_alphabetic(cp) or unicode_is_decimal_number(cp) or unicode_is_mark(cp)

fn unicode_canonical_combining_class(cp: i64) -> i64:
    val index = _unicode_find(_unicode_ccc_keys, cp)
    if index < 0: return 0
    _unicode_ccc_values[index]

fn _unicode_decompose_one(cp: i64) -> [i64]:
    val s_index = cp - 0xAC00
    val n_count: i64 = 588
    if s_index >= 0 and s_index < 11172:
        var result: [i64] = [0x1100 + s_index / n_count, 0x1161 + (s_index % n_count) / 28]
        if s_index % 28 != 0: result.push(0x11A7 + s_index % 28)
        return result
    val index = _unicode_find(_unicode_decomposition_keys, cp)
    if index < 0: return [cp]
    var result: [i64] = []
    var cursor = _unicode_decomposition_offsets[index]
    val finish = _unicode_decomposition_offsets[index + 1]
    while cursor < finish:
        val nested = _unicode_decompose_one(_unicode_decomposition_data[cursor])
        var nested_index: i64 = 0
        while nested_index < nested.len():
            result.push(nested[nested_index])
            nested_index = nested_index + 1
        cursor = cursor + 1
    result

fn _unicode_compose_pair(first: i64, second: i64) -> i64:
    val l_index = first - 0x1100
    val v_index = second - 0x1161
    if l_index >= 0 and l_index < 19 and v_index >= 0 and v_index < 21:
        return 0xAC00 + (l_index * 21 + v_index) * 28
    val s_index = first - 0xAC00
    val t_index = second - 0x11A7
    if s_index >= 0 and s_index < 11172 and s_index % 28 == 0 and t_index > 0 and t_index < 28:
        return first + t_index
    var low: i64 = 0
    var high: i64 = _unicode_composition_data.len() / 3 - 1
    while low <= high:
        val mid = (low + high) / 2
        val offset = mid * 3
        val left = _unicode_composition_data[offset]
        val right = _unicode_composition_data[offset + 1]
        if first < left or (first == left and second < right): high = mid - 1
        elif first > left or (first == left and second > right): low = mid + 1
        else: return _unicode_composition_data[offset + 2]
    -1

fn unicode_normalize_nfc(input: text) -> text:
    val input_codepoints = text_codepoints(input)
    var values: [i64] = []
    var input_index: i64 = 0
    while input_index < input_codepoints.len():
        val expanded = _unicode_decompose_one(input_codepoints[input_index])
        var expanded_index: i64 = 0
        while expanded_index < expanded.len():
            values.push(expanded[expanded_index])
            expanded_index = expanded_index + 1
        input_index = input_index + 1
    var order_index: i64 = 1
    while order_index < values.len():
        val cls = unicode_canonical_combining_class(values[order_index])
        var move_index = order_index
        if cls != 0:
            while move_index > 0 and unicode_canonical_combining_class(values[move_index - 1]) > cls:
                val previous = values[move_index - 1]
                values[move_index - 1] = values[move_index]
                values[move_index] = previous
                move_index = move_index - 1
        order_index = order_index + 1
    if values.len() == 0: return ""
    var output: [i64] = [values[0]]
    var starter_index: i64 = 0
    var starter = values[0]
    var last_class: i64 = 0
    var index: i64 = 1
    while index < values.len():
        val cp = values[index]
        val cls = unicode_canonical_combining_class(cp)
        val composite = _unicode_compose_pair(starter, cp)
        if composite >= 0 and (last_class < cls or last_class == 0):
            output[starter_index] = composite
            starter = composite
        else:
            if cls == 0:
                starter_index = output.len()
                starter = cp
            output.push(cp)
            last_class = cls
        index = index + 1
    text_from_codepoints(output)

fn _unicode_is_final_sigma(values: [i64], index: i64) -> bool:
    var before = false
    var cursor = index - 1
    while cursor >= 0:
        if not _unicode_range_contains(_unicode_case_ignorable_ranges, values[cursor]):
            before = _unicode_range_contains(_unicode_cased_ranges, values[cursor])
            break
        cursor = cursor - 1
    if not before: return false
    cursor = index + 1
    while cursor < values.len():
        if not _unicode_range_contains(_unicode_case_ignorable_ranges, values[cursor]):
            return not _unicode_range_contains(_unicode_cased_ranges, values[cursor])
        cursor = cursor + 1
    true

fn unicode_default_lowercase(input: text) -> text:
    val values = text_codepoints(unicode_normalize_nfc(input))
    var output: [i64] = []
    var value_index: i64 = 0
    while value_index < values.len():
        val cp = values[value_index]
        val table_index = _unicode_find(_unicode_lowercase_keys, cp)
        if table_index < 0:
            output.push(cp)
        else:
            var start = _unicode_lowercase_offsets[table_index]
            var finish = _unicode_lowercase_offsets[table_index + 1]
            if _unicode_lowercase_conditions[table_index] == 1 and _unicode_is_final_sigma(values, value_index):
                start = _unicode_lowercase_conditional_offsets[table_index]
                finish = _unicode_lowercase_conditional_offsets[table_index + 1]
                var conditional_index = start
                while conditional_index < finish:
                    output.push(_unicode_lowercase_conditional_data[conditional_index])
                    conditional_index = conditional_index + 1
            else:
                var mapping_index = start
                while mapping_index < finish:
                    output.push(_unicode_lowercase_data[mapping_index])
                    mapping_index = mapping_index + 1
        value_index = value_index + 1
    unicode_normalize_nfc(text_from_codepoints(output))

export unicode_is_alphabetic, unicode_is_decimal_number, unicode_is_mark,
       unicode_is_token_code_point, unicode_canonical_combining_class,
       unicode_normalize_nfc, unicode_default_lowercase
`;

function main() {
  const out = args();
  const sourceBytes = Object.fromEntries(SOURCE_NAMES.map((name) => [name, readFileSync(join(out.ucd, name))]));
  const source = Object.fromEntries(Object.entries(sourceBytes).map(([name, bytes]) => [name, bytes.toString("utf8")]));
  const records = parseUnicodeData(source["UnicodeData.txt"]);
  const exclusions = new Set(source["CompositionExclusions.txt"].split(/\r?\n/).map(strip).filter(Boolean).map((v) => Number.parseInt(v, 16)));
  const alphabetic = parseProperty(source["DerivedCoreProperties.txt"], "Alphabetic");
  const softDotted = parseProperty(source["PropList.txt"], "Soft_Dotted");
  const cased = parseProperty(source["DerivedCoreProperties.txt"], "Cased");
  const caseIgnorable = parseProperty(source["DerivedCoreProperties.txt"], "Case_Ignorable");
  const decimal = mergeRanges(records.filter(({ f }) => f[2] === "Nd").map(({ cp }) => [cp, cp]));
  const marks = mergeRanges(records.filter(({ f }) => f[2].startsWith("M")).map(({ cp }) => [cp, cp]));
  const ccc = records.filter(({ f }) => f[3] !== "0").map(({ cp, f }) => [cp, Number(f[3])]);
  const decomposition = [];
  const lowerMap = new Map();
  for (const { cp, f } of records) {
    if (f[5] && !f[5].startsWith("<")) decomposition.push([cp, cps(f[5])]);
    if (f[13]) lowerMap.set(cp, { mapping: [Number.parseInt(f[13], 16)], conditional_mapping: null, condition: null });
  }
  for (const raw of source["SpecialCasing.txt"].split(/\r?\n/)) {
    const line = strip(raw);
    if (!line) continue;
    const f = line.split(";").map((v) => v.trim());
    const conditionTokens = f[4] ? f[4].split(/\s+/) : [];
    if (conditionTokens.some((v) => /^[a-z]{2,3}(?:-[A-Za-z0-9]+)*$/.test(v))) continue;
    const cp = Number.parseInt(f[0], 16), condition = conditionTokens.join(" ") || null;
    if (condition) {
      const prior = lowerMap.get(cp) ?? { mapping: [cp], conditional_mapping: null, condition: null };
      lowerMap.set(cp, { ...prior, conditional_mapping: cps(f[1]), condition });
    } else lowerMap.set(cp, { mapping: cps(f[1]), conditional_mapping: null, condition: null });
  }
  const compositions = [];
  for (const [composed, parts] of decomposition) {
    if (parts.length === 2 && !exclusions.has(composed) &&
        (ccc.find(([cp]) => cp === composed)?.[1] ?? 0) === 0 &&
        (ccc.find(([cp]) => cp === parts[0])?.[1] ?? 0) === 0)
      compositions.push([parts[0], parts[1], composed]);
  }
  compositions.sort((a, b) => a[0] - b[0] || a[1] - b[1]);
  const lowercase = [...lowerMap].map(([cp, value]) => [cp, value.mapping, value.conditional_mapping, value.condition]).sort((a, b) => a[0] - b[0]);
  const tables = {
    ALPHABETIC_RANGES: alphabetic, DECIMAL_NUMBER_RANGES: decimal, MARK_RANGES: marks,
    SOFT_DOTTED_RANGES: softDotted, CASED_RANGES: cased,
    CASE_IGNORABLE_RANGES: caseIgnorable, CANONICAL_COMBINING_CLASS: ccc,
    CANONICAL_DECOMPOSITIONS: decomposition, CANONICAL_COMPOSITIONS: compositions,
    DEFAULT_LOWERCASE: lowercase,
    HANGUL_NFC: { s_base: 0xAC00, l_base: 0x1100, v_base: 0x1161, t_base: 0x11A7, l_count: 19, v_count: 21, t_count: 28 }
  };
  const generatorBytes = readFileSync(fileURLToPath(import.meta.url));
  const meta = { unicode_version: VERSION, generator_version: GENERATOR_VERSION, generator_sha256: sha(generatorBytes) };
  const jsBytes = Buffer.from(renderJs(meta, tables));
  const simpleBytes = Buffer.from(renderSimple(meta, tables));
  mkdirSync(dirname(out.js), { recursive: true });
  mkdirSync(dirname(out.simple), { recursive: true });
  mkdirSync(dirname(out.manifest), { recursive: true });
  writeFileSync(out.js, jsBytes);
  writeFileSync(out.simple, simpleBytes);
  const manifest = {
    schema: "spipe-unicode-table-manifest-v1", unicode_version: VERSION,
    upstream: { repository: "https://github.com/unicode-org/unicodetools", commit: "2c1309ab2ac1de5c62f09089c8ed6bf6f1d37920", path: `unicodetools/data/ucd/${VERSION}` },
    license: { spdx: "Unicode-3.0", file: "examples/05_stdlib/spipe/tools/unicode/UNICODE-LICENSE.txt" },
    generator: { version: GENERATOR_VERSION, file: "examples/05_stdlib/spipe/tools/unicode/generate_unicode_tables.mjs", sha256: sha(generatorBytes), command: "node examples/05_stdlib/spipe/tools/unicode/generate_unicode_tables.mjs" },
    sources: SOURCE_NAMES.map((name) => ({ name, sha256: sha(sourceBytes[name]), bytes: sourceBytes[name].length })),
    generated: [
      { file: "examples/05_stdlib/spipe/src/search/generated/unicode_17_0_0.js", sha256: sha(jsBytes), bytes: jsBytes.length },
      { file: "src/lib/common/search/generated/unicode_17_0_0.spl", sha256: sha(simpleBytes), bytes: simpleBytes.length }
    ],
    contracts: { normalization: "NFC", case_conversion: "Default Lowercase Conversion", case_folding_used: false, token_properties: ["Alphabetic", "Decimal_Number", "Mark", "LOW_LINE"] }
  };
  writeFileSync(out.manifest, `${JSON.stringify(manifest, null, 2)}\n`);
  process.stdout.write(`generated Unicode ${VERSION}: ${tables.CANONICAL_DECOMPOSITIONS.length} decompositions, ${lowercase.length} lowercase mappings\n`);
}

main();
